apiVersion: v1
kind: Service
metadata:  
  name: http
spec:
  selector:    
    app: frontend
  type: NodePort
  ports:  
  - name: http
    port: 3000
    nodePort: 30036
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: joboonja-frontend
        image: quay.io/amirhmi/jobunja_ui:latest
        resources:
          requests:
            memory: "33Mi"
            cpu: "0.05"
          limits:
            cpu: "0.05"
            memory: "35Mi"
        ports:
        - containerPort: 3000